modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="philiaamulet"
version="1.20.1-1.0.7"
logoFile="logo.png" #optional
displayName="PhiLia Amulet"
authors="Rinko1231"
description='''
Prevents friendly fire chaos among a player's pets and summons, and adds an amulet that protects specific mobs from player damage.
'''